description = "現在のブランチをレビューする"

# language=markdown
prompt = """
1. 情報収集と分析
    あなたが以下の情報を自動的に収集・分析する。bashコマンドで各情報を取得する。bashコマンド以外は使わない。

    ```bash
    !{git branch --show-current}
    !{git diff main}
    ```

2. ブランチの変更内容の確認
    現在のブランチにコミットされている内容を確認し、あなたがレビューする。
    コミットされていないファイルに関しては無視する。

3. 結果報告
    レビュー内容をまとめて、下記のテンプレートでユーザーに報告する。
    ```
    ファイルのフルパス:行数
    内容
    ```
"""
